### ISSUE TITLE
Does not work in 1.21.4

### ISSUE THREAD

**Issue by amqndin** [MulverineX/player_motion#15]
upon running this nothing happened.
![image](https://github.com/user-attachments/assets/f6449af8-c828-4c7c-b774-f20cd067074e)
tested in vanilla
![image](https://github.com/user-attachments/assets/3486193e-6025-49b2-9f2c-e95d52b386f5)

**Comment by amqndin** [comment]
```[15:08:11] [Render thread/ERROR]:
Failed to load function player_motion:internal/launch/main
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Whilst parsing command on line 18: Can't find element 'minecraft:generic.knockback_resistance' of type 'minecraft:attribute' at position 41: ...resistance<--[HERE]
at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) ~[?:?]
at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Whilst parsing command on line 18: Can't find element 'minecraft:generic.knockback_resistance' of type 'minecraft:attribute' at position 41: ...resistance<--[HERE]
at knot/net.minecraft.class_2158.method_9195(class_2158.java:80) ~[client-intermediary.jar:?]
at knot/net.minecraft.class_5349.method_29451(class_5349.java:87) ~[client-intermediary.jar:?]
... 7 more```
there is this error log upon reloading the datapack

**Comment by amqndin** [comment]
i understand the error now, i will open a pr for fixing this

**Comment by amqndin** [comment]
turns out this was already fixed here on github, but it is still broken in latest release on modrinth. thats why i was confused. sorry to bother
